#include <stdint.h>	 /* Declarations of uint_32 and the like */
#include <pic32mx.h> /* Declarations of system-specific addresses etc */
#include "gameheader.h"
#include <stdlib.h>
#include "sprites.h"
#include "graphics.h"
#include <stdbool.h>
#include "io.h"
/* Non-Maskable Interrupt; something bad likely happened, so hang */
void _nmi_handler() {
	for(;;);
}

/* This function is called upon reset, before .data and .bss is set up */
void _on_reset() {
	
}
#define io32(x) (*(volatile unsigned int *)(x))
#define addr1 (0xbf886100)
#define addr2 (0xbf886110)
/* This function is called before main() is called, you can do setup here */
void _on_bootstrap()
{

	/*
	We're unsure of what is needed in here, but the lab files we based our game off of needed them,
	 and it is easier to just let it be then to figure out what breaks.
	*/
	SYSKEY = 0xAA996655; /* Unlock OSCCON, step 1 */
	SYSKEY = 0x556699AA; /* Unlock OSCCON, step 2 */
	while (OSCCON & (1 << 21))
		;				  /* Wait until PBDIV ready */
	OSCCONCLR = 0x180000; /* clear PBDIV bit <0,1> */
	while (OSCCON & (1 << 21))
		;		  /* Wait until PBDIV ready */
	SYSKEY = 0x0; /* Lock OSCCON */

	/* Output pins for display signals */
	PORTF = 0xFFFF;
	PORTG = (1 << 9);
	ODCF = 0x0;
	ODCG = 0x0;
	TRISFCLR = 0x70;
	TRISGCLR = 0x200;

	/* Set up input pins */
	TRISDSET = (1 << 8);
	TRISFSET = (1 << 1);

	/* Set up SPI as master */
	SPI2CON = 0;
	SPI2BRG = 4;
	/* SPI2STAT bit SPIROV = 0; */
	SPI2STATCLR = 0x40;
	/* SPI2CON bit CKP = 1; */
	SPI2CONSET = 0x40;
	/* SPI2CON bit MSTEN = 1; */
	SPI2CONSET = 0x20;
	/* SPI2CON bit ON = 1; */
	SPI2CONSET = 0x8000;

	/* Set up i2c */
	I2C1CON = 0x0;
	/* I2C Baud rate should be less than 400 kHz (master sets the limit), is generated by dividing
	the 40 MHz peripheral bus clock down */
	// These bits control the divider function of the Peripheral Clock.
	I2C1BRG = 0x0C2;
	// Transmit Buffer Full Status bit, 0 = Transmit complete; I2CxTRN register is empty.
	I2C1STAT = 0x0;
	// Stop in Idle Mode bit, 1 = Discontinue module operation when the device enters Idle mode
	I2C1CONSET = 1 << 13; // SIDL = 1
	// I2C Enable bit, 1 = Enables the I2C module and configures the SDAx and SCLx pins as serial port pins
	I2C1CONSET = 1 << 15; // ON = 1

	io32(addr1) = 0x00; // Initialises Port E so all bits are outputs
	io32(addr2) = 0x00; // Sets each bit of Port E to 0

	/*TRISD &= 0b111111100000;

	T2CON = 0x0;
	T2CONSET = 0x0070;
	TMR2 = 0x0000;
	PR2 = 0x7A12; // 80MHz/256/10

	IPCSET(2) = 0x0000000D;

	IFSCLR(0) = 0x00000108;
	IECSET(0) = 0x00000100;

	T2CONSET = 0x8000;*/
}
